# Generated by Django 5.1.3 on 2025-01-29 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 9, 45, 16, 100901)),
        ),
    ]
