# Generated by Django 5.1.3 on 2025-02-05 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 9, 41, 24, 288357)),
        ),
    ]
