# Generated by Django 5.1.3 on 2025-02-05 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0003_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 10, 57, 50, 280684)),
        ),
    ]
