# Generated by Django 5.1.3 on 2025-02-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0004_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 11, 17, 5, 780136)),
        ),
    ]
