# Generated by Django 5.1.3 on 2025-01-15 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articolo_visualizzazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 1, 15, 9, 21, 42, 473997)),
        ),
    ]
