# Generated by Django 5.1.3 on 2025-01-15 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_giornalista_anno_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 1, 15, 9, 37, 40, 255258)),
        ),
    ]
