# Generated by Django 5.1.3 on 2025-01-15 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articolo_data_alter_giornalista_anno_nascita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='data',
        ),
        migrations.AddField(
            model_name='articolo',
            name='data_articolo',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 1, 15, 9, 50, 55, 976706)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 1, 15, 9, 50, 55, 976706)),
        ),
    ]
