# Generated by Django 5.1.3 on 2025-01-22 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_articolo_data_articolo_data_articolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_articolo',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 43, 55, 677023)),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='visualizzazioni',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 9, 43, 55, 677023)),
        ),
    ]
