# Generated by Django 5.1.3 on 2025-02-05 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_articolo_data_articolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_articolo',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 9, 41, 24, 288357)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 9, 41, 24, 288357)),
        ),
    ]
