# Generated by Django 5.1.3 on 2025-02-12 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_articolo_data_articolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_articolo',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 9, 42, 33, 623175)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='anno_nascita',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 9, 42, 33, 623175)),
        ),
    ]
