# Generated by Django 5.1.3 on 2025-02-12 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 10, 3, 28, 847601)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 10, 3, 28, 847601)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='titolo',
            field=models.CharField(max_length=50),
        ),
    ]
