# Generated by Django 5.1.3 on 2025-02-12 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0002_alter_corso_data_fine_alter_corso_data_inizio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 11, 39, 22, 175163)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 11, 39, 22, 175163)),
        ),
    ]
